services:
  - type: web
    name: faredown-booking-app
    env: node
    repo: https://github.com/Pikateck/faredown-booking-app
    branch: main
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
