services:
  - type: web
    name: faredown-booking-app
    env: node
    buildCommand: "./build.sh"
    startCommand: "node dist/server/production.mjs"
    envVars:
      - key: NODE_VERSION
        value: 18

